apply plugin: 'org.springframework.boot'
dependencies {
    implementation project(":api-rest")
    implementation project(":cloud-provider")
    implementation project(":jwt-provider")
    implementation project(":azure-provider")
    implementation project(":aws-provider")
    implementation project(":gcp-provider")
    implementation project(":usecase")
    implementation project(":model")
    implementation project(":jpa-repository")
    implementation ("org.springframework.boot:spring-boot-starter")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
}